'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {UtensilsCrossed,House,CalendarDays,Vote,Sparkles,ArrowUpRight,Plus,ChevronLeft,ChevronRight,Copy,Check,Leaf,Sun,Sunrise,Moon,Users,Settings2,ArrowRight,RefreshCw,Loader2,LogOut,ShoppingBasket,Droplets,Heart,ChefHat,WashingMachine} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {DAYS,SLOTS,MENU,weekOf,dateAt,todayISO,sampleData} from '@/lib/flat-data';
import SignIn from './sign-in';
import LaundryPanel from './laundry-panel';
const mealIcons=[Sunrise,Sun,Moon];
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string,label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={'avatar a'+index%4}>{name?.slice(0,1).toUpperCase()||'?'}</span>}
function shortDate(s:string){return new Date(s+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'});}
export default function FlatApp(){
 const [data,setData]=useState<any>(null),[demo,setDemo]=useState(true),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[tab,setTab]=useState('menu'),[week,setWeek]=useState(weekOf()),[selected,setSelected]=useState((new Date(todayISO()+'T12:00:00').getDay()+6)%7),[modal,setModal]=useState(''),[form,setForm]=useState<any>({}),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const requestVersion=useRef(0);
 const mutationPending=useRef(false);
 const [selectedFlat,setSelectedFlat]=useState('');
 const activeFlat=useRef('');
 const switchFlat=(id:string)=>{if(busy)return;requestVersion.current++;activeFlat.current=id;setSelectedFlat(id);setModal('');setError('');setData(null);setDemo(true);setLoading(true);setTab('menu')};
 const load=useCallback(async(silent=false)=>{if(mutationPending.current)return;const version=++requestVersion.current;if(!silent)setLoading(true);try{const res=await fetch('/api/flat?week='+week+(selectedFlat?'&flatId='+encodeURIComponent(selectedFlat):''));const d:any=await res.json();if(version!==requestVersion.current)return;if(!res.ok){if(res.status===403||res.status===404){activeFlat.current='';setSelectedFlat('');setData(null);setDemo(true);setNotice('Flat access changed. Loading your remaining flats.');}throw new Error(d.error);}if(version!==requestVersion.current)return;activeFlat.current=d.flat?.id||'';setData(d);setDemo(!d.flat);setError('');}catch(e){if(version===requestVersion.current&&!silent)setError((e as Error).message||'Could not load your flat.');}finally{if(version===requestVersion.current)setLoading(false)}},[week,selectedFlat]);
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('login_error')){setNotice('Sign-in did not finish. Please try again.');window.history.replaceState({},'',window.location.pathname)}load();const id=setInterval(()=>load(true),30000);return()=>clearInterval(id)},[load]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id)},[notice]);
 const d=demo?sampleData():data;const me=d?.members?.find((m:any)=>m.id===d.user?.userId);const owner=d?.flat?.owner===d?.user?.userId;const members=d?.members||[];const meals=d?.meals||[];const requests=d?.requests||[];const duties=d?.duties||[];const currentWeek=demo?weekOf():week;const openRequests=requests.filter((r:any)=>r.status==='open');
 const open=(kind:string,values:any={})=>{setError('');setForm(values);setModal(kind)};
 const resident=me?.role!=='cook';const kitchen=owner||me?.role==='cook';const residents=members.filter((m:any)=>m.role!=='cook');
 const start=(kind:string)=>open(kind,{name:data?.user?.fullName?.split(' ')[0]||'',flatName:'',number:'',code:''});
 async function action(payload:any){if(demo&&!['create','join'].includes(payload.action)){setNotice('This is a sample flat. Create or join your flat to save changes.');start('create');return false;}if(busy||loading)return false;setBusy(true);mutationPending.current=true;const version=++requestVersion.current;setError('');try{const r=await fetch('/api/flat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,week,flatId:activeFlat.current})});const result:any=await r.json();if(!r.ok)throw new Error(result.error);if(version!==requestVersion.current)return false;activeFlat.current=result.flat?.id||'';setSelectedFlat(activeFlat.current);setData(result);setDemo(!result.flat);setNotice(payload.action==='leave'?'You left the flat.':payload.action==='delete'?'The flat was deleted for everyone.':payload.action==='transfer_owner'?'Ownership transferred.':payload.action==='create'?'Your flat is ready. Copy the join code to invite your flatmates.':payload.action==='join'?'Welcome to your flat!':'Saved for everyone in your flat.');return true;}catch(e){setError((e as Error).message);return false;}finally{mutationPending.current=false;setBusy(false)}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const control=new AbortController();Promise.resolve(context.registerTool({name:'view_flat_section',description:'Open the weekly menu, meal votes, kitchen duties or flatmate preferences without changing saved data.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['menu','votes','kitchen','laundry','flat']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input:any){if(!['menu','votes','kitchen','laundry','flat'].includes(input?.section))throw new Error('Invalid section');setTab(input.section);return {section:input.section};}},{signal:control.signal})).catch(()=>{});return()=>control.abort()},[]);
 const requestMeal=(day=selected,slot=2)=>open('request',{day:String(day),slot:String(slot),title:'',reason:''});
 async function copy(){if(demo){start('create');return}try{await navigator.clipboard.writeText(form.inviteRole==='cook'?d.flat.cookCode:d.flat.code);setNotice('Join code copied. Share it with your flatmates.')}catch{open('invite')}}
 function field(label:string,key:string,placeholder='',required=false){return <label className="field">{label}<input value={form[key]||''} required={required} maxLength={key==='number'?20:key==='name'?40:key==='flatName'?60:120} placeholder={placeholder} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>}
 const toggleDuty=(x:any)=>action({action:'duty',id:x.id,done:!x.done});
 const dutyList=(rows:any[])=>rows.length?rows.map((x:any)=>{const member=members.find((m:any)=>m.id===x.assignee)||(d.formerMembers||[]).find((m:any)=>m.id===x.assignee);const can=owner||x.assignee===d.user.userId;return <div className={'duty-row '+(x.done?'completed':'')} key={x.id}><Checkbox disabled={busy||!can} checked={!!x.done} onCheckedChange={()=>toggleDuty(x)} aria-label={'Mark '+SLOTS[x.slot]+' washing '+(x.done?'incomplete':'complete')}/><div className="duty-info"><b>{SLOTS[x.slot]} clean-up</b><span>{x.utensils}</span><div className="assigned"><Avatar name={member?.name||'Former flatmate'} index={Math.max(0,members.indexOf(member))}/><span>{member?.name||'Former flatmate'}{x.assignee===d.user.userId?' (you)':''}</span>{x.done&&<em>Done</em>}</div></div>{owner&&<button className="icon-btn" aria-label="Reassign duty or edit utensils" onClick={()=>open('duty',x)}><Settings2 size={16}/></button>}</div>}):<div className="empty-small">Duties appear when your flat starts this week’s plan.</div>;
 if(loading&&!data)return <div className="app-shell"><main><p role="status">Loading your flats…</p></main></div>;
 return <div className="app-shell">
 <header className="topbar"><a href="/" className="brand"><span className="brand-icon"><UtensilsCrossed size={22}/></span>flat<span className="amp">&</span>fork<span className="brand-dot">.</span></a><div className="top-right"><span className="home-pill"><House size={15}/>{demo?'Sample flat':`Flat ${d?.flat?.number} · ${resident?'Resident':'Cook'}`}</span>{!demo&&<button className="icon-btn" title="Refresh flat" onClick={()=>load()}><RefreshCw size={17} className={loading?'spinning':''}/></button>}<button className="profile-button" aria-label="Open my food preferences" onClick={()=>demo?start('create'):open('profile',me)}><Avatar name={demo?'O':me?.name}/></button></div></header>
 <main>
 <div className="intro-row"><div><div className="eyebrow"><span className="tiny-line"/> THE SHARED KITCHEN, SORTED</div><h1>A little planning.<br className="mobile-break"/> A happier flat.</h1><p>Good food, everyone’s say, and no mystery dishes in the sink.</p></div><div className="intro-actions">{demo?<><button className="button ghost" onClick={()=>start('join')}>Join a flat</button><button className="button primary" onClick={()=>start('create')}><Plus size={17}/>Create your flat</button></>:<button className="button primary" onClick={()=>resident?open('invite',{inviteRole:'resident'}):setTab('flat')}><Users size={17}/>{resident?'Invite flatmates':'Our flat'}</button>}</div></div>
 {error&&!modal&&<div className="error" role="alert">{error}<button onClick={()=>load()}>Try again</button></div>}
 {data?.user&&<section className="flat-manager" aria-label="My flats"><label className="field">My flats<select aria-label="Switch flat" value={data.flat?.id||''} disabled={busy||loading} onChange={e=>switchFlat(e.target.value)}>{!data.flat&&<option value="">No flat selected</option>}{(data.flats||[]).map((f:any)=><option key={f.id} value={f.id}>{f.name} · {f.number}{f.owner===data.user.userId?' (owner)':''}</option>)}</select></label><button className="button ghost" disabled={busy||loading} onClick={()=>start('create')}><Plus size={16}/>Create another flat</button><button className="button ghost" disabled={busy||loading} onClick={()=>start('join')}>Join another flat</button></section>}
 <div className="flat-strip"><div className="flat-strip-left"><div className="small-house"><House size={19}/></div><div><strong>{demo?'Take a look around':d?.flat.name}</strong><span>{demo?'You’re exploring a sample flat. Your own starts empty.':`Flat ${d?.flat.number} · ${members.length} ${members.length===1?'flatmate':'flatmates'}`}</span></div></div><div className="flat-strip-right"><div className="avatar-stack">{members.slice(0,4).map((m:any,i:number)=><Avatar name={m.name} index={i} key={m.id}/>)}</div><button className="text-button" onClick={()=>demo?start('create'):resident?copy():setTab('flat')}>{demo?'Make it yours':resident?`Join code · ${d?.flat.code}`:'Cook account'} {demo?<ArrowUpRight size={16}/>:<Copy size={15}/>}</button></div></div>
 <Tabs value={tab} onValueChange={setTab}><div className="nav-row"><TabsList className="main-tabs" variant="line"><TabsTrigger value="menu"><CalendarDays/>Weekly menu</TabsTrigger><TabsTrigger value="votes"><Vote/>Meal requests{openRequests.length>0&&<span className="tab-count">{openRequests.length}</span>}</TabsTrigger><TabsTrigger value="kitchen"><Droplets/>Kitchen duties</TabsTrigger>{resident&&<TabsTrigger value="laundry"><WashingMachine/>Laundry turns</TabsTrigger>}<TabsTrigger value="flat"><Users/>Our flat</TabsTrigger></TabsList><span className="nav-note"><Leaf size={14}/>Made for living together</span></div></Tabs>
 <div key={tab} className="page-enter" role="tabpanel" aria-label={tab}>
 {tab==='menu'&&<>
 <div className="overview-grid"><section className="food-feature"><img src="/indian-thali.jpg" alt="A home-cooked Indian thali with rice, roti and vegetable curries"/><div className="food-shade"/><div className="food-copy"><span className="feature-kicker"><ChefHat size={15}/> YOUR FLAT’S TABLE</span><h2>“Aaj kya<br/>banega?”<span>Sorted.</span></h2><p>One menu. Fewer group-chat debates.</p><button className="feature-button" onClick={()=>requestMeal()}>Suggest a meal <ArrowUpRight size={17}/></button></div><span className="photo-label">A little taste of home</span></section>
 <section className="today-card panel"><div className="section-title"><div><span className="eyebrow">{dateAt(currentWeek,selected)===todayISO()?'ON THE TABLE TODAY':DAYS[selected].toUpperCase()+"’S MENU"}</span><h2>{DAYS[selected]}, {shortDate(dateAt(currentWeek,selected))}</h2></div><span className="round-icon"><UtensilsCrossed size={21}/></span></div><div className="today-meals">{SLOTS.map((slot,i)=>{const Icon=mealIcons[i];const meal=meals.find((m:any)=>m.day===selected&&m.slot===i);return <button className="today-meal" key={slot} onClick={()=>resident?requestMeal(selected,i):open('meal',{...meal})}><span className={'meal-icon m'+i}><Icon size={18}/></span><div><span>{slot} <small>{['8:30 am','1:00 pm','8:30 pm'][i]} · suggested time</small></span><b>{meal?.title||'Not planned yet'}{meal?.prepared&&<span className="prepared-label">Prepared <Check size={12}/></span>}</b></div><ArrowUpRight size={16}/></button>})}</div><div className="today-foot"><Leaf size={14}/><span>Check everyone’s preferences before sharing with your cook.</span></div></section></div>
 <div className="content-grid"><section className="panel week-panel"><div className="section-title"><div><h2>This week’s menu</h2><p>A plan everyone can have a say in.</p></div><div className="week-controls"><button className="icon-btn" disabled={demo||loading||busy} aria-label="Previous week" onClick={()=>setWeek(dateAt(week,-7))}><ChevronLeft size={17}/></button><span>{shortDate(currentWeek)} – {shortDate(dateAt(currentWeek,6))}</span><button className="icon-btn" disabled={demo||loading||busy} aria-label="Next week" onClick={()=>setWeek(dateAt(week,7))}><ChevronRight size={17}/></button></div></div>
 {!meals.length?<div className="empty-state"><CalendarDays size={30}/><h3>A fresh week, a fresh menu.</h3><p>{kitchen?'Start with a vegetarian Indian menu and rotating dish duties. Then let everyone suggest changes.':'Your cook or flat creator can start this week’s menu and dishwashing rotation.'}</p>{kitchen&&<button disabled={busy} className="button primary" onClick={()=>action({action:'plan'})}><Plus size={16}/>Start this week’s plan</button>}</div>:<div className="table-wrap"><table className="menu-table"><thead><tr><th>DAY</th>{SLOTS.map((s,i)=>{const Icon=mealIcons[i];return <th key={s}><span><Icon size={15}/>{s}</span></th>})}</tr></thead><tbody>{DAYS.map((day,i)=><tr className={selected===i?'selected-day':''} key={day}><th><button className="day-button" onClick={()=>setSelected(i)}><b>{day.slice(0,3)}</b><span>{shortDate(dateAt(currentWeek,i))}</span>{dateAt(currentWeek,i)===todayISO()&&<em>Today</em>}</button></th>{SLOTS.map((s,j)=><td key={s}><button className="menu-cell" onClick={()=>resident?requestMeal(i,j):open('meal',{...meals.find((m:any)=>m.day===i&&m.slot===j)})}>{meals.find((m:any)=>m.day===i&&m.slot===j)?.title||'Not planned'}<span className="cell-edit"><Plus size={13}/></span></button></td>)}</tr>)}</tbody></table></div>}
 <div className="panel-footer"><span><Sparkles size={14}/>Have something else in mind?</span><button className="text-button" onClick={()=>requestMeal()}>Request a change <ArrowRight size={14}/></button></div></section>
 <aside className="right-column"><section className="panel cleanup-card"><div className="section-title"><div><span className="eyebrow">EVERYONE PITCHES IN</span><h2>{resident?'Who’s on dishes?':'Today’s cooking'}</h2></div><Droplets className="green" size={23}/></div><p className="subtle">{DAYS[selected]} · shared utensils & clean-up</p>{resident?dutyList(duties.filter((x:any)=>x.day===selected)):<div className="empty-small">{meals.filter((m:any)=>m.day===selected&&m.prepared).length} of 3 meals prepared. Open a meal to update its status.</div>}<button className="full-text-link" onClick={()=>setTab('kitchen')}>{resident?'See the weekly rotation':'Open the kitchen'} <ArrowRight size={15}/></button></section><section className="vote-teaser"><span className="vote-circle"><Vote size={21}/></span><h3>A change on the menu?</h3><p>{openRequests.length?`${openRequests.length} ${openRequests.length===1?'request is':'requests are'} waiting for your flat’s votes.`:'Suggest a swap. Give everyone a say.'}</p><button className="text-button" onClick={()=>setTab('votes')}>Have your say <ArrowUpRight size={16}/></button></section></aside></div></>}
 {tab==='votes'&&<section className="panel section-panel"><div className="section-title"><div><span className="eyebrow">EVERY PLATE GETS A VOTE</span><h2>Meal requests</h2><p>More than half the residents must support a change. Your cook or flat creator applies it.</p></div><button className="button primary" onClick={()=>requestMeal()}><Plus size={17}/>Suggest a change</button></div><div className="week-label">Week of {shortDate(currentWeek)}</div>{requests.length?<div className="request-grid">{requests.map((r:any)=><article className="request-card" key={r.id}><div className="request-meta"><span>{DAYS[r.day]} · {SLOTS[r.slot]}</span><span className={'badge '+(r.status==='applied'?'green-badge':'')}>{r.status==='applied'?'On the menu':'Open vote'}</span></div><h3>{r.title}</h3><p>{r.reason||'Let’s try something different.'}</p><div className="request-author"><Avatar name={r.name||me?.name} index={1}/><span>Suggested by {r.name||me?.name}</span></div><div className="vote-track"><span style={{width:Math.min(100,r.votes/residents.length*100)+'%'}}/></div><div className="vote-stats"><b>{r.votes} of {residents.length} residents in favour</b><span>{Math.floor(residents.length/2)+1} votes needed</span></div>{r.status==='open'&&<div className="request-actions"><button disabled={busy||!resident} className={'button '+(r.mine?'voted':'ghost')} onClick={()=>action({action:'vote',id:r.id,support:!r.mine})}>{r.mine?<Check size={16}/>:<Heart size={16}/>} {!resident?'Residents vote':r.mine?'Supported · undo':'Sounds good'}</button>{kitchen&&<button disabled={busy||r.votes<=residents.length/2} className="button primary" onClick={()=>action({action:'apply',id:r.id})}>Apply to menu</button>}</div>}</article>)}</div>:<div className="empty-state"><Vote size={34}/><h3>No meal debates. Yet.</h3><p>Ask for your favourite dish or suggest a swap for the week.</p><button className="button ghost" onClick={()=>requestMeal()}>Make the first suggestion</button></div>}</section>}
 {tab==='kitchen'&&<div className="content-grid"><section className="panel section-panel"><div className="section-title"><div><span className="eyebrow">A FAIR SHARE OF THE SINK</span><h2>{resident?'The dishwashing rota':'The cook’s checklist'}</h2><p>{resident?'Lunch and dinner clean-up, rotated across your flatmates.':'Review the week’s meals and mark each one prepared.'}</p></div><Droplets size={30} className="green"/></div><div className="week-label">Week of {shortDate(currentWeek)} · {resident?duties.filter((x:any)=>x.done).length:meals.filter((m:any)=>m.prepared).length} / {resident?duties.length:meals.length} completed</div>{!resident?<div className="rota-grid">{DAYS.map((day,i)=><section className="rota-day" key={day}><h3>{day}<span>{shortDate(dateAt(currentWeek,i))}</span></h3>{meals.filter((m:any)=>m.day===i).map((m:any)=><label className="supply" key={m.id}><Checkbox checked={!!m.prepared} disabled={busy} onCheckedChange={()=>action({action:'prepared',id:m.id,prepared:!m.prepared})}/><span>{SLOTS[m.slot]} · {m.title}</span></label>)}</section>)}</div>:duties.length?<div className="rota-grid">{DAYS.map((day,i)=><section className="rota-day" key={day}><h3>{day}<span>{shortDate(dateAt(currentWeek,i))}</span></h3>{dutyList(duties.filter((x:any)=>x.day===i))}</section>)}</div>:<div className="empty-state"><Droplets size={32}/><h3>No dishes assigned yet.</h3><p>Start a weekly menu to generate the rotation.</p><button className="button ghost" onClick={()=>setTab('menu')}>Go to weekly menu</button></div>}</section><aside><section className="panel supplies"><div className="section-title"><h2>Kitchen essentials</h2><ShoppingBasket size={23}/></div><p className="subtle">Running low? Put it on the list.</p>{d.supplies.map((s:any)=><label className={'supply '+(s.done?'completed':'')} key={s.id}><Checkbox checked={!!s.done} disabled={busy} onCheckedChange={()=>action({action:'supply',id:s.id,done:!s.done})}/><span>{s.title}</span></label>)}{!d.supplies.length&&<p className="empty-small">Your shared shopping list is empty.</p>}<button className="button ghost wide" onClick={()=>open('supply',{title:''})}><Plus size={16}/>Add an item</button></section><div className="kitchen-note"><Sparkles size={22}/><h3>Leave it ready for the next meal.</h3><p>Wash shared utensils, wipe the counter, and put things back. Your future hungry self says thanks.</p></div></aside></div>}
 {tab==='laundry'&&resident&&<LaundryPanel key={d.flat?.id} data={d} week={currentWeek} setWeek={setWeek} action={action} busy={busy} demo={demo} error={error}/>}
 {tab==='flat'&&<section className="panel section-panel"><div className="section-title"><div><span className="eyebrow">DIFFERENT TASTES. ONE TABLE.</span><h2>Meet your flat’s appetites</h2><p>Share likes, dislikes, and allergies so your cook has the full picture.</p></div><button className="button primary" onClick={()=>demo?start('create'):open('profile',me)}><Settings2 size={16}/>My preferences</button></div><div className="members-grid">{members.map((m:any,i:number)=><article className="member-card" key={m.id}><div className="member-header"><Avatar name={m.name} index={i}/><div><h3>{m.name} {m.id===d.user.userId&&<small>(you)</small>}</h3><span>{m.id===d.flat.owner?'Resident · Flat creator':m.role==='cook'?'Cook':'Resident'}</span></div><span className="badge green-badge">{m.diet}</span></div><dl><dt><Heart size={14}/>Always up for</dt><dd>{m.likes||'No favourites shared yet'}</dd><dt>Would rather skip</dt><dd>{m.avoid||'Nothing listed'}</dd><dt>Allergies</dt><dd className={m.allergies?'allergy':''}>{m.allergies||'None reported'}</dd></dl></article>)}</div><div className="flat-bottom"><p>Preferences are shared with your flat. Menus are not automatically checked for allergens; review ingredients with your cook.</p>{resident&&<button className="button ghost" onClick={()=>demo?start('create'):open('invite',{inviteRole:'resident'})}><Users size={16}/>Invite a flatmate</button>}</div>{!demo&&<div className="flat-management-actions">{owner?<><p>You own this flat. Transfer ownership before leaving, or delete it for everyone.</p>{residents.some((m:any)=>m.id!==me.id)&&<button className="button ghost" disabled={busy||loading} onClick={()=>open('transfer_owner',{target:residents.find((m:any)=>m.id!==me.id)?.id})}>Transfer ownership</button>}<button className="button danger" disabled={busy||loading} onClick={()=>open('delete',{confirmName:''})}>Delete this flat</button></>:<button className="button ghost" disabled={busy||loading} onClick={()=>open('leave')}>Leave this flat</button>}</div>}{!demo&&<button className="signout text-button" onClick={async()=>{await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});window.location.href='/'}}><LogOut size={15}/>Sign out</button>}</section>}
 </div>
 <footer><span className="footer-brand">flat & fork.</span><span>A home runs better together.</span><a href="https://unsplash.com/photos/bKmSUcAGrvI" target="_blank" rel="noreferrer">Photo: fuseviews / Unsplash</a></footer>
 </main>
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy){setModal('');setError('')}}}><DialogContent className="flat-dialog"><DialogHeader><DialogTitle>{({create:'Make room for good food.',join:'Your flat is waiting.',request:'What are you craving?',profile:'Your seat at the table.',invite:'Better with your flatmates.',duty:'Share the clean-up.',supply:'Add a kitchen essential.',meal:'Ready for the table?',leave:'Leave this flat?',delete:'Delete this flat for everyone?',transfer_owner:'Transfer flat ownership?'} as any)[modal]||'Your flat'}</DialogTitle><DialogDescription>{({create:'Create your shared kitchen and get a unique join code.',join:'Ask your flatmate for the join code, then make yourself at home.',request:'Your flatmates can vote on this change before it reaches the menu.',profile:'Help your flat and cook plan meals you’ll enjoy.',invite:'Send this code to your flatmates. They sign in and choose “Join a flat”.',duty:'Choose who takes this turn and what needs cleaning.',supply:'Keep everyone in the loop about what’s running low.',meal:'Let your residents know when this meal is prepared.',leave:'You will lose access to this flat. Other members and your other flats stay. You can rejoin with an invitation code.',delete:'This permanently removes this flat and its shared data for every member. Your account and other flats stay.',transfer_owner:'The selected resident becomes the owner. You remain a resident and can then leave.'} as any)[modal]}</DialogDescription></DialogHeader>
 {(modal==='create'||modal==='join')&&!data?.user?<SignIn auth={data?.auth} onSuccess={()=>load()}/>:<form onSubmit={async e=>{e.preventDefault();let payload:any;if(modal==='request')payload={...form,action:'request',day:Number(form.day),slot:Number(form.slot)};else if(modal==='profile')payload={...form,action:'profile'};else if(modal==='duty')payload={action:'duty',id:form.id,assignee:form.assignee,utensils:form.utensils};else payload={...form,action:modal};if(await action(payload))setModal('')}}>
 {modal==='leave'&&<p className="form-note">Pending future chores will be reassigned. Previous turns and completed chores keep their history.</p>}
 {modal==='delete'&&<><p className="form-note">To confirm, type the exact flat name: <strong>{d.flat?.name}</strong></p>{field('Flat name confirmation','confirmName','',true)}</>}
 {modal==='transfer_owner'&&<label className="field">New owner<Picker label="New owner" value={form.target||''} onChange={v=>setForm({...form,target:v})} options={residents.filter((m:any)=>m.id!==me.id).map((m:any)=>({value:m.id,label:m.name}))}/></label>}
 {modal==='create'&&<>{field('Your name','name','Om',true)}{field('Flat name','flatName','The hungry bunch',true)}{field('Flat / house number','number','402',true)}<p className="form-note">Your flat starts empty. You can add a starter menu after inviting everyone.</p></>}
 {modal==='join'&&<>{field('Your name','name','Your first name',true)}{field('Resident or cook join code','code','Paste the code you were given',true)}<p className="form-note">Your join code determines whether you join as a resident or cook.</p></>}
 {modal==='request'&&<><div className="form-row"><label className="field">Day<Picker label="Day" value={form.day||'0'} onChange={v=>setForm({...form,day:v})} options={DAYS.map((x,i)=>({value:String(i),label:x}))}/></label><label className="field">Meal<Picker label="Meal" value={form.slot||'0'} onChange={v=>setForm({...form,slot:v})} options={SLOTS.map((x,i)=>({value:String(i),label:x}))}/></label></div>{field('Suggested dish','title','e.g. Chole & jeera rice',true)}{field('Why the change? (optional)','reason','Anything your flatmates should know?')}<div className="form-note">For the week of {shortDate(currentWeek)}. Your suggestion includes your vote.</div></>}
 {modal==='profile'&&<>{field('Your name','name','',true)}<label className="field">Food preference<Picker label="Food preference" value={form.diet||'Vegetarian'} onChange={v=>setForm({...form,diet:v})} options={['Vegetarian','Vegan','Eggetarian','Non-vegetarian','No preference'].map(x=>({value:x,label:x}))}/></label>{field('Favourite foods','likes','Paneer, dal chawal, dosa…')}{field('Foods you prefer to avoid','avoid','e.g. Bitter gourd')}{field('Allergies','allergies','e.g. Peanuts — leave blank if none')}</>}
 {modal==='duty'&&<><label className="field">Assigned flatmate<Picker label="Assigned flatmate" value={form.assignee||''} onChange={v=>setForm({...form,assignee:v})} options={residents.map((m:any)=>({value:m.id,label:m.name}))}/></label>{field('Utensils & areas to clean','utensils','Plates, bowls, kadai & countertop',true)}</>}
 {modal==='meal'&&<div className="invite-box"><ChefHat size={26}/><h3>{form.title||'No meal planned yet'}</h3>{form.id&&<button type="button" className="button primary wide" disabled={busy} onClick={async()=>{if(await action({action:'prepared',id:form.id,prepared:!form.prepared}))setModal('')}}><Check size={16}/>{form.prepared?'Mark not prepared':'Mark as prepared'}</button>}</div>}
 {modal==='supply'&&field('Item','title','e.g. Dishwash liquid',true)}
 {modal==='invite'&&<div className="invite-box"><House size={27}/><h3>{d.flat.name} · {d.flat.number}</h3>{owner&&<label className="field wide">Invite as<Picker label="Invite role" value={form.inviteRole||'resident'} onChange={v=>setForm({...form,inviteRole:v})} options={[{value:'resident',label:'Resident of this house'},{value:'cook',label:'Cook'}]}/></label>}<div className="join-code">{form.inviteRole==='cook'?d.flat.cookCode:d.flat.code}</div><button className="button primary wide" type="button" onClick={copy}><Copy size={16}/>Copy join code</button><p>Share the resident code with housemates and the cook code with your cook. Each code grants the matching role.</p></div>}
 {error&&<div className="error" role="alert">{error}</div>}
 {modal!=='invite'&&modal!=='meal'&&<button type="submit" className="button primary wide submit" disabled={busy||loading||(modal==='delete'&&form.confirmName!==d.flat?.name)}>{busy?<Loader2 size={17} className="spinning"/>:<Check size={17}/>} {busy?'Saving…':({create:'Create flat',join:'Join flat',request:'Send for a vote',profile:'Save my preferences',duty:'Save duty',supply:'Add to list',leave:'Leave flat',delete:'Permanently delete flat',transfer_owner:'Transfer ownership'} as any)[modal]}</button>}
 </form>}
 </DialogContent></Dialog>
 </div>
}

