'use client';
import {useState} from 'react';
import {WashingMachine,Wind,ArrowRight,ChevronLeft,ChevronRight,ChevronUp,ChevronDown,Plus,Settings2,Check,Loader2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {DAYS,todayISO,dateAt} from '@/lib/flat-data';
function dateLabel(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'})}
function Pick({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
export default function LaundryPanel({data,week,setWeek,action,busy,demo,error}:{data:any;week:string;setWeek:(s:string)=>void;action:(b:any)=>Promise<boolean>;busy:boolean;demo:boolean;error:string}){
 const residents=data.members.filter((m:any)=>m.role!=='cook');const owner=data.flat.owner===data.user.userId;const [modal,setModal]=useState('');const [f,setF]=useState<any>({});
 const name=(id:string)=>residents.find((m:any)=>m.id===id)?.name||(data.formerMembers||[]).find((m:any)=>m.id===id)?.name||'Former flatmate';
 const start=()=>{if(demo){void action({action:'laundry_schedule'});return;}const c=data.laundryConfig;const order=residents.map((m:any)=>m.id);setF({start:c?dateAt(todayISO(),1):todayISO(),days:c?.days||[0,2,4],dryOffset:c?.dryOffset??1,washOrder:order,dryOrder:order});setModal('schedule')};
 function move(key:string,i:number,delta:number){const next=[...f[key]],j=i+delta;if(j<0||j>=next.length)return;[next[i],next[j]]=[next[j],next[i]];setF({...f,[key]:next})}
 return <>
 <div className="laundry-next-grid">{(['wash','dry'] as const).map(kind=>{const Icon=kind==='wash'?WashingMachine:Wind;const next=data.laundryNext?.[kind]||[];return <section className="panel laundry-next" key={kind}><div className="section-title"><div><span className="eyebrow">{kind==='wash'?'WASHING TURN':'DRYING TURN'}</span><h2>{next[0]?name(next[0].assignee):'No turn scheduled'}</h2></div><span className="round-icon"><Icon size={23}/></span></div><p className="subtle">{next[0]?dateLabel(next[0].date)+(next[0].date===todayISO()?' · Today':''):'Set your days and rotation below.'}</p><div className="next-person"><span>Up next</span><ArrowRight size={15}/><b>{next[1]?name(next[1].assignee):'No following turn yet'}</b>{next[1]&&<span>{dateLabel(next[1].date)}</span>}</div></section>})}</div>
 <section className="panel section-panel"><div className="section-title"><div><span className="eyebrow">ONE LESS “WHOSE TURN?”</span><h2>Clothes washing & drying</h2><p>Fixed days, a rotating order, and room to swap when plans change.</p></div>{owner&&<button className="button primary" onClick={start}><Settings2 size={16}/>{data.laundryConfig?'Set future rotation':'Set laundry days'}</button>}</div>
 <div className="laundry-toolbar"><div className="week-controls"><button className="icon-btn" disabled={busy||demo} aria-label="Previous laundry week" onClick={()=>setWeek(dateAt(week,-7))}><ChevronLeft size={17}/></button><span>{dateLabel(week)} – {dateLabel(dateAt(week,6))}</span><button className="icon-btn" disabled={busy||demo} aria-label="Next laundry week" onClick={()=>setWeek(dateAt(week,7))}><ChevronRight size={17}/></button></div><span className="subtle">{(data.laundry||[]).filter((x:any)=>x.done).length} / {(data.laundry||[]).length} done this week</span></div>
 {(data.laundry||[]).length?<div className="laundry-list">{data.laundry.map((x:any)=>{const Icon=x.kind==='wash'?WashingMachine:Wind;const can=owner||x.assignee===data.user.userId;return <div className={'laundry-row '+(x.done?'completed':'')} key={x.id}><Checkbox checked={!!x.done} disabled={busy||!can} onCheckedChange={()=>action({action:'laundry',id:x.id,date:x.date,done:!x.done})} aria-label={'Mark '+x.kind+' turn for '+name(x.assignee)+(x.done?' incomplete':' complete')}/><span className="laundry-kind"><Icon size={19}/>{x.kind==='wash'?'Washing':'Drying'}</span><div className="laundry-date"><b>{dateLabel(x.date)}</b><span>{x.date===todayISO()?'Today':x.date<todayISO()&&!x.done?'Overdue':x.done?'Completed':'Scheduled'}</span></div><div className="laundry-assignee"><b>{name(x.assignee)}{x.assignee===data.user.userId?' (you)':''}</b><span>{x.note||'Part of the shared rotation'}</span></div><button className="button ghost" disabled={busy} onClick={()=>{if(demo){void action({action:'laundry'});return;}setF(x);setModal('turn')}}><Settings2 size={14}/>Change turn</button></div>})}</div>:<div className="empty-state"><WashingMachine size={33}/><h3>{data.laundryConfig?'No laundry on these dates.':'Make laundry days predictable.'}</h3><p>{data.laundryConfig?'Try another week or set a future rotation.':owner?'Choose washing days, when drying happens, and the order of residents. Future turns will follow automatically.':'Your flat creator can set the days and rotation. Then residents can change individual turns.'}</p>{owner&&!data.laundryConfig&&<button className="button ghost" onClick={start}><Plus size={17}/>Set up the rotation</button>}</div>}
 <div className="form-note">Residents can manually reassign a turn. Only the assigned resident or flat creator can mark it done. “Up next” shows the next uncompleted future turn.</div>
 </section>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="flat-dialog"><DialogHeader><DialogTitle>{modal==='schedule'?'Your days. Your rotation.':'Change this laundry turn.'}</DialogTitle><DialogDescription>{modal==='schedule'?'Everyone gets a turn. Dragging isn’t needed—use the arrows to set the order.':'This changes only this turn; the regular rotation stays the same.'}</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();const payload=modal==='schedule'?{action:'laundry_schedule',...f}:{action:'laundry',id:f.id,date:f.date,assignee:f.assignee,note:f.note||''};if(await action(payload))setModal('')}}>
 {modal==='schedule'?<><label className="field">Start date<input type="date" required min={todayISO()} max={dateAt(todayISO(),90)} value={f.start||''} onChange={e=>setF({...f,start:e.target.value})}/></label><fieldset className="days-fieldset"><legend>Washing days</legend><div className="day-picks">{DAYS.map((day,i)=><label key={day}><Checkbox checked={(f.days||[]).includes(i)} onCheckedChange={v=>setF({...f,days:v?[...f.days,i]:f.days.filter((d:number)=>d!==i)})}/>{day.slice(0,3)}</label>)}</div></fieldset><label className="field">Drying day<Pick label="Drying day" value={String(f.dryOffset??1)} onChange={v=>setF({...f,dryOffset:Number(v)})} options={[{value:'0',label:'Same day as washing'},{value:'1',label:'The next day'},{value:'2',label:'Two days after washing'}]}/></label>{['washOrder','dryOrder'].map(key=><div className="rotation-order" key={key}><h3>{key==='washOrder'?'Washing order':'Drying order'}</h3>{(f[key]||[]).map((id:string,i:number)=><div className="rotation-person" key={id}><span>{i+1}</span><b>{name(id)}</b><button type="button" className="icon-btn" aria-label={'Move '+name(id)+' earlier'} disabled={i===0} onClick={()=>move(key,i,-1)}><ChevronUp size={16}/></button><button type="button" className="icon-btn" aria-label={'Move '+name(id)+' later'} disabled={i===f[key].length-1} onClick={()=>move(key,i,1)}><ChevronDown size={16}/></button></div>)}</div>)}{data.laundryConfig&&<p className="form-note">The new order applies from this start date. Earlier turns stay in the previous rotation. Use “Change turn” for a one-time swap.</p>}</>:<><label className="field">Resident<Pick label="Resident" value={f.assignee||''} onChange={v=>setF({...f,assignee:v})} options={residents.map((m:any)=>({value:m.id,label:m.name}))}/></label><label className="field">Note (optional)<input value={f.note||''} maxLength={240} placeholder="e.g. Swapped because I’m away" onChange={e=>setF({...f,note:e.target.value})}/></label></>}
 <div role="alert">{error&&<div className="error">{error}</div>}</div><button className="button primary wide submit" disabled={busy||(modal==='schedule'&&!f.days?.length)}>{busy?<Loader2 size={16} className="spinning"/>:<Check size={16}/>}Save {modal==='schedule'?'rotation':'turn'}</button>
 </form></DialogContent></Dialog>
 </>
}

