'use client';
import {useRef} from 'react';
import {CalendarDays,ChevronDown,ChevronLeft,ChevronRight,Droplets,House,LayoutDashboard,Settings2,Users,Vote,WashingMachine,ArrowUpRight} from 'lucide-react';
import {dateAt,weekOf} from '@/lib/flat-data';
export const SECTIONS=[{id:'home',label:'Overview',icon:LayoutDashboard,description:'Your day, at a glance'},{id:'menu',label:'Meal planner',icon:CalendarDays,description:'Plan what’s on the table'},{id:'votes',label:'Meal requests',icon:Vote,description:'Decide together'},{id:'kitchen',label:'Kitchen duties',icon:Droplets,description:'Share the clean-up'},{id:'laundry',label:'Laundry',icon:WashingMachine,description:'Wash, dry and hand over'},{id:'flat',label:'Flatmates',icon:Users,description:'Your people & preferences'}];
type NavProps={section:string;resident:boolean;flatName:string;flatNumber:string;name:string;role:string;votes:number;onNavigate:(section:string)=>void;onManage:()=>void;onProfile:()=>void;busy:boolean};
export function WorkspaceNav(p:NavProps){
 const disclosure=useRef<HTMLDetailsElement>(null);const sections=SECTIONS.filter(s=>p.resident||s.id!=='laundry');
 const choose=(section:string)=>{p.onNavigate(section);if(disclosure.current)disclosure.current.open=false;};
 const links=<>{sections.map(({id,label,icon:Icon})=><button key={id} onClick={()=>choose(id)} aria-current={p.section===id?'page':undefined} className={'workspace-nav-link '+(p.section===id?'active':'')}><Icon size={19}/><span>{label}</span>{id==='votes'&&p.votes>0&&<em>{p.votes}</em>}</button>)}</>;
 return <><aside className="workspace-sidebar" aria-label="Workspace sidebar"><div className="sidebar-flat"><span className="sidebar-house"><House size={22}/></span><div><b>{p.flatName}</b><small>Flat {p.flatNumber}</small></div></div><p className="sidebar-label">WORKSPACE</p><nav aria-label="Main navigation">{links}</nav><div className="sidebar-management"><p className="sidebar-label">YOUR HOME</p><button className="workspace-nav-link" onClick={p.onManage} disabled={p.busy}><Settings2 size={19}/><span>Manage flat</span><ArrowUpRight size={16}/></button><p>Invitations, flat switching and membership settings.</p></div><button className="sidebar-profile" onClick={p.onProfile}><span>{p.name.slice(0,1).toUpperCase()}</span><div><b>{p.name}</b><small>{p.role} · My profile</small></div><ChevronRight size={17}/></button></aside><details className="mobile-workspace-nav" ref={disclosure}><summary><span><House size={17}/>{SECTIONS.find(s=>s.id===p.section)?.label||'Workspace'}</span><span>Menu <ChevronDown size={17}/></span></summary><nav aria-label="Mobile navigation">{links}<button className="workspace-nav-link" onClick={()=>{p.onManage();if(disclosure.current)disclosure.current.open=false}} disabled={p.busy}><Settings2 size={19}/><span>Manage flat</span></button></nav></details></>;
}
export function FilterBar({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string;count?:number}[]}){return <div className="filter-bar" role="group" aria-label={label}>{options.map(o=><button key={o.value} aria-pressed={value===o.value} className={value===o.value?'selected':''} onClick={()=>onChange(o.value)}>{o.label}{o.count!==undefined&&<span>{o.count}</span>}</button>)}</div>}
export function SectionMetrics({items}:{items:{label:string;value:number|string;hint?:string}[]}){return <div className="section-metrics">{items.map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.hint&&<small>{item.hint}</small>}</div>)}</div>}
export function WeekToolbar({week,onChange,disabled}:{week:string;onChange:(week:string)=>void;disabled:boolean}){const label=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});return <div className="workspace-week"><div><CalendarDays size={18}/><span>{label(week)} – {label(dateAt(week,6))}</span></div><div className="workspace-week-actions"><button className="button ghost" disabled={disabled||week===weekOf()} onClick={()=>onChange(weekOf())}>This week</button><button className="icon-btn" aria-label="Previous week" disabled={disabled} onClick={()=>onChange(dateAt(week,-7))}><ChevronLeft size={19}/></button><button className="icon-btn" aria-label="Next week" disabled={disabled} onClick={()=>onChange(dateAt(week,7))}><ChevronRight size={19}/></button></div></div>}
