export const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export const SLOTS=['Breakfast','Lunch','Dinner'];
export const MENU=[['Poha & chai','Dal tadka & rice','Roti & paneer bhurji'],['Idli & chutney','Rajma chawal','Aloo gobi & roti'],['Aloo paratha','Chole & rice','Veg pulao & raita'],['Upma & chai','Sambar rice','Dal fry & roti'],['Toast & chai','Kadhi khichdi','Paneer curry & roti'],['Dosa & chutney','Veg biryani','Pav bhaji'],['Paratha & curd','Chole bhature','Light khichdi']];
export function todayISO(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function weekOf(date=todayISO()){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}
export function dateAt(week:string,day:number){const d=new Date(week+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+day);return d.toISOString().slice(0,10);}
function baseSampleData(){const week=weekOf();return {demo:true,user:{userId:'demo',displayName:'Om'},flat:{id:'demo-flat',name:'The good-food flat',number:'402',code:'DEMO402',owner:'demo'},members:[{id:'demo',name:'Om',diet:'Vegetarian',likes:'Paneer, rajma chawal',avoid:'',allergies:''},{id:'a',name:'Aarav',diet:'Vegetarian',likes:'Dosa, chole',avoid:'Bitter gourd',allergies:''},{id:'r',name:'Rohan',diet:'No preference',likes:'Biryani',avoid:'',allergies:''},{id:'k',name:'Kunal',diet:'Vegetarian',likes:'Pav bhaji',avoid:'',allergies:'Peanuts'}],meals:MENU.flatMap((row,day)=>row.map((title,slot)=>({id:`demo-${day}-${slot}`,day,slot,title,week,flat_id:'demo-flat'}))),requests:[{id:'demo-request',day:4,slot:2,title:'Chole & jeera rice',reason:'Something different for Friday?',name:'Aarav',status:'open',week,votes:2,mine:0}],duties:DAYS.flatMap((_,day)=>[1,2].map((slot,i)=>({id:`d-${day}-${slot}`,day,slot,assignee:['demo','a','r','k'][(day*2+i)%4],done:0,utensils:'Plates, bowls, kadai & countertop'}))),supplies:[{id:'s1',title:'Dishwash liquid',done:0},{id:'s2',title:'Scrub pads',done:0},{id:'s3',title:'Garbage bags',done:1}]};}

export function sampleData(){const d:any=baseSampleData();d.members=d.members.map((m:any)=>({...m,role:'resident'}));d.members.push({id:'cook-demo',name:'Meena',role:'cook',diet:'Vegetarian',likes:'',avoid:'',allergies:''});d.flat.cookCode='DEMOCOOK';const week=weekOf();const tasks:any[]=[];for(let i=0;i<21;i++)if([0,2,4].includes(i%7)){const index=tasks.length/2;tasks.push({id:'sample-wash-'+i,date:dateAt(week,i),kind:'wash',assignee:d.members[index%4].id,done:false,note:''},{id:'sample-dry-'+i,date:dateAt(week,i+1),kind:'dry',assignee:d.members[(index+1)%4].id,done:false,note:''})}d.laundry=tasks.filter(t=>t.date<=dateAt(week,6));d.laundryNext={wash:tasks.filter(t=>t.kind==='wash'&&t.date>=todayISO()).slice(0,2),dry:tasks.filter(t=>t.kind==='dry'&&t.date>=todayISO()).slice(0,2)};d.laundryConfig={start:week,days:[0,2,4],dryOffset:1,washOrder:d.members.slice(0,4).map((m:any)=>m.id),dryOrder:d.members.slice(0,4).map((m:any)=>m.id)};return d;}
